# Generated by Django 5.2.7 on 2025-10-14 12:30

import medication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_remove_medicationhistory_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.CharField(default=medication.models.generate_medication_id, editable=False, help_text='Unique identifier for the medication (e.g., MED-ABC12345)', max_length=12, primary_key=True, serialize=False),
        ),
    ]
