# Generated by Django 5.2.7 on 2025-11-09 17:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_alter_medication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage_amount',
            field=models.DecimalField(decimal_places=3, help_text='Dosage amount (numeric value)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
