# Generated by Django 5.2.7 on 2025-10-17 22:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the template', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('medication_reminder', 'Medication Reminder'), ('health_tip', 'Health Tip'), ('sync_complete', 'Sync Complete'), ('general', 'General')], help_text='Type of notification this template is for', max_length=50)),
                ('title_template', models.CharField(help_text="Title template with placeholders (e.g., 'Time to take {medication_name}')", max_length=200)),
                ('message_template', models.TextField(help_text='Message template with placeholders')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the template was last updated')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the notification', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('medication_reminder', 'Medication Reminder'), ('health_tip', 'Health Tip'), ('sync_complete', 'Sync Complete'), ('general', 'General')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', help_text='Delivery status of the notification', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When the notification should be sent (null for immediate)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was actually sent', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data related to the notification (e.g., medication_id, article_id)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the notification was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the notification was last updated')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the log entry', primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS')], help_text='Method used to deliver the notification', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], help_text='Delivery status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', null=True)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response data from delivery service')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the delivery was attempted')),
                ('notification', models.ForeignKey(help_text='Notification this log entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the preference', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('medication_reminder', 'Medication Reminder'), ('health_tip', 'Health Tip'), ('sync_complete', 'Sync Complete'), ('general', 'General')], help_text='Type of notification this preference applies to', max_length=50)),
                ('push_enabled', models.BooleanField(default=True, help_text='Whether push notifications are enabled for this type')),
                ('email_enabled', models.BooleanField(default=False, help_text='Whether email notifications are enabled for this type')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Whether SMS notifications are enabled for this type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the preference was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the preference was last updated')),
                ('user', models.ForeignKey(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
                'ordering': ['user', 'notification_type'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the device token', primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Device token for push notifications', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text='Type of device', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device token is active')),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now, help_text='When this token was last used')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the token was registered')),
                ('user', models.ForeignKey(help_text='User this device belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'db_table': 'device_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx'), models.Index(fields=['token'], name='device_toke_token_e218ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'status'], name='notificatio_type_18e5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_3d00b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
    ]
