# Generated by Django 5.2.7 on 2025-10-14 13:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import health_records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.CharField(default=health_records.models.generate_health_record_id, editable=False, help_text='Unique identifier for the health record (e.g., HR-ABC12345)', max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the health record', max_length=200)),
                ('type', models.CharField(choices=[('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('imaging', 'Imaging'), ('vaccination', 'Vaccination'), ('other', 'Other')], default='other', help_text='Type of health record', max_length=50)),
                ('date', models.DateField(help_text='Date of the health record')),
                ('description', models.TextField(blank=True, help_text='Description of the health record')),
                ('file', models.FileField(blank=True, help_text='Uploaded file for the health record', null=True, upload_to=health_records.models.health_record_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'doc', 'docx', 'txt'])])),
                ('file_name', models.CharField(blank=True, help_text='Original name of the uploaded file', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the health record')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this health record', on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_records_healthrecord',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='health_reco_user_id_3355e9_idx'), models.Index(fields=['user', 'date'], name='health_reco_user_id_9d6e7d_idx'), models.Index(fields=['title'], name='health_reco_title_0eed63_idx')],
            },
        ),
    ]
