# Generated by Django 5.2.7 on 2025-11-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='file',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='file_name',
        ),
    ]
