# Generated by Django 5.2.7 on 2025-11-09 17:30

from django.db import migrations, models, connection


def add_type_field_if_not_exists(apps, schema_editor):
    """Add type field only if it doesn't exist"""
    db_connection = schema_editor.connection
    with db_connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='health_records_healthrecord' 
            AND column_name='type'
        """)
        exists = cursor.fetchone()
        
        if not exists:
            # Add the column
            cursor.execute("""
                ALTER TABLE health_records_healthrecord 
                ADD COLUMN type VARCHAR(50) DEFAULT 'other' 
                NOT NULL
            """)
            # Add check constraint for choices
            try:
                cursor.execute("""
                    ALTER TABLE health_records_healthrecord 
                    ADD CONSTRAINT health_records_healthrecord_type_check 
                    CHECK (type IN ('lab_result', 'prescription', 'imaging', 'vaccination', 'other'))
                """)
            except Exception:
                # Constraint might already exist, ignore
                pass


def remove_type_field(apps, schema_editor):
    """Remove type field if it exists"""
    db_connection = schema_editor.connection
    with db_connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='health_records_healthrecord' 
            AND column_name='type'
        """)
        exists = cursor.fetchone()
        
        if exists:
            cursor.execute("""
                ALTER TABLE health_records_healthrecord 
                DROP COLUMN IF EXISTS type CASCADE
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_remove_healthrecord_file_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_type_field_if_not_exists,
            reverse_code=remove_type_field
        ),
    ]
