# Generated by Django 5.2.7 on 2025-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_remove_healthrecord_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='type',
            field=models.CharField(
                choices=[
                    ('lab_result', 'Lab Result'),
                    ('prescription', 'Prescription'),
                    ('imaging', 'Imaging'),
                    ('vaccination', 'Vaccination'),
                    ('other', 'Other')
                ],
                default='other',
                help_text='Type of health record',
                max_length=50
            ),
        ),
    ]
