# Generated by Django 5.2.7 on 2025-11-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_remove_healthrecord_file_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Add column if it doesn't exist
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='health_records_healthrecord' 
                        AND column_name='type'
                    ) THEN
                        ALTER TABLE health_records_healthrecord 
                        ADD COLUMN type VARCHAR(50) DEFAULT 'other' NOT NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE health_records_healthrecord 
                DROP COLUMN IF EXISTS type CASCADE;
            """
        ),
    ]
