# Generated by Django 5.2.7 on 2025-11-09 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import health_records.models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_add_type_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the table if it exists
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS health_records_healthrecord CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Recreate the table with correct schema
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.CharField(default=health_records.models.generate_health_record_id, editable=False, help_text='Unique identifier for the health record (e.g., HR-ABC12345)', max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the health record', max_length=200)),
                ('type', models.CharField(choices=[('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('imaging', 'Imaging'), ('vaccination', 'Vaccination'), ('other', 'Other')], default='other', help_text='Type of health record', max_length=50)),
                ('date', models.DateField(help_text='Date of the health record')),
                ('description', models.TextField(blank=True, help_text='Description of the health record')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the health record')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this health record', on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_records_healthrecord',
                'ordering': ['-date', '-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'type'], name='health_reco_user_id_3355e9_idx'),
                    models.Index(fields=['user', 'date'], name='health_reco_user_id_9d6e7d_idx'),
                    models.Index(fields=['title'], name='health_reco_title_0eed63_idx'),
                ],
            },
        ),
    ]
