# Generated by Django 5.2.7 on 2025-10-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(default='temp_id', editable=False, help_text='Short public identifier for the user', max_length=12, unique=True),
        ),
    ]
