# Generated by Django 5.2.7 on 2025-10-14 11:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the medication', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the medication', max_length=200)),
                ('medication_type', models.CharField(choices=[('Pill', 'Pill'), ('Injection', 'Injection'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Cream', 'Cream'), ('Spray', 'Spray')], default='Pill', help_text='Type of medication', max_length=50)),
                ('dosage_amount', models.DecimalField(decimal_places=3, help_text='Dosage amount (numeric value)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('dosage_unit', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('mcg', 'mcg'), ('g', 'g'), ('IU', 'IU'), ('units', 'units'), ('tablets', 'tablets'), ('capsules', 'capsules'), ('drops', 'drops'), ('puffs', 'puffs'), ('applications', 'applications')], default='mg', help_text='Unit of measurement for dosage', max_length=20)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('As needed', 'As needed')], default='Daily', help_text='How often the medication should be taken', max_length=50)),
                ('start_date', models.DateField(help_text='Date when medication should start')),
                ('end_date', models.DateField(blank=True, help_text='Date when medication should end (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions')),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Whether reminders are enabled for this medication')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this medication is currently active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this medication', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medication_medication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the history record', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('taken', 'Taken'), ('skipped', 'Skipped'), ('reminder_sent', 'Reminder Sent')], help_text='Action that was performed', max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medication', models.ForeignKey(help_text='Medication this history record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='medication.medication')),
            ],
            options={
                'verbose_name': 'Medication History',
                'verbose_name_plural': 'Medication Histories',
                'db_table': 'medication_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the interaction', primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], help_text='Severity of the interaction', max_length=20)),
                ('description', models.TextField(help_text='Description of the interaction')),
                ('recommendation', models.TextField(help_text='Recommendation for handling the interaction')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medication1', models.ForeignKey(help_text='First medication in the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_primary', to='medication.medication')),
                ('medication2', models.ForeignKey(help_text='Second medication in the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_secondary', to='medication.medication')),
            ],
            options={
                'verbose_name': 'Medication Interaction',
                'verbose_name_plural': 'Medication Interactions',
                'db_table': 'medication_interaction',
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the reminder', primary_key=True, serialize=False)),
                ('time', models.TimeField(help_text='Time when reminder should be sent')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reminder is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medication', models.ForeignKey(help_text='Medication this reminder belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_times', to='medication.medication')),
            ],
            options={
                'verbose_name': 'Medication Reminder',
                'verbose_name_plural': 'Medication Reminders',
                'db_table': 'medication_reminder',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationTaken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the taken record', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date when medication was taken')),
                ('taken', models.BooleanField(default=False, help_text='Whether the medication was taken')),
                ('time_taken', models.TimeField(blank=True, help_text='Actual time when medication was taken', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about taking the medication')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(help_text='Medication that was taken', on_delete=django.db.models.deletion.CASCADE, related_name='taken_records', to='medication.medication')),
            ],
            options={
                'verbose_name': 'Medication Taken',
                'verbose_name_plural': 'Medications Taken',
                'db_table': 'medication_taken',
                'ordering': ['-date', '-time_taken'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['user', 'start_date'], name='medication__user_id_ee1f91_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['user', 'is_active'], name='medication__user_id_2ba3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['start_date', 'end_date'], name='medication__start_d_5968b8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationhistory',
            index=models.Index(fields=['medication', 'created_at'], name='medication__medicat_32621d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationhistory',
            index=models.Index(fields=['action', 'created_at'], name='medication__action_efcfae_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinteraction',
            index=models.Index(fields=['medication1', 'severity'], name='medication__medicat_e1fe73_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinteraction',
            index=models.Index(fields=['severity'], name='medication__severit_3fc871_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationinteraction',
            unique_together={('medication1', 'medication2')},
        ),
        migrations.AlterUniqueTogether(
            name='medicationreminder',
            unique_together={('medication', 'time')},
        ),
        migrations.AddIndex(
            model_name='medicationtaken',
            index=models.Index(fields=['medication', 'date'], name='medication__medicat_e83772_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationtaken',
            index=models.Index(fields=['date', 'taken'], name='medication__date_a60a35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationtaken',
            unique_together={('medication', 'date')},
        ),
    ]
