# Generated by Django 5.2.7 on 2025-10-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationhistory',
            name='medication',
        ),
        migrations.AlterUniqueTogether(
            name='medicationinteraction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='medicationinteraction',
            name='medication1',
        ),
        migrations.RemoveField(
            model_name='medicationinteraction',
            name='medication2',
        ),
        migrations.AlterModelOptions(
            name='medicationtaken',
            options={'ordering': ['-date'], 'verbose_name': 'Medication Taken', 'verbose_name_plural': 'Medications Taken'},
        ),
        migrations.RemoveIndex(
            model_name='medication',
            name='medication__start_d_5968b8_idx',
        ),
        migrations.RemoveField(
            model_name='medicationtaken',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicationtaken',
            name='time_taken',
        ),
        migrations.DeleteModel(
            name='MedicationHistory',
        ),
        migrations.DeleteModel(
            name='MedicationInteraction',
        ),
    ]
