# Generated by Django 5.2.7 on 2025-10-16 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the emergency contact', max_length=100)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to the user (e.g., Spouse, Parent, Friend)', max_length=50)),
                ('phone_number', models.CharField(help_text='Phone number of the emergency contact', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address of the emergency contact (optional)', max_length=254)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary emergency contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this contact was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this contact was last updated')),
                ('user', models.ForeignKey(help_text='The user who owns this emergency contact', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'db_table': 'emergency_contacts',
                'ordering': ['-is_primary', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'is_primary'), name='unique_primary_contact_per_user')],
            },
        ),
    ]
