# Generated by Django 5.2.7 on 2025-10-16 00:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the medical condition', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the medical condition', max_length=200)),
                ('diagnosed_date', models.DateField(help_text='Date when the condition was diagnosed')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], default='active', help_text='Current status of the condition', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the condition', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who has this condition', on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Condition',
                'verbose_name_plural': 'Medical Conditions',
                'db_table': 'medical_conditions',
                'ordering': ['-diagnosed_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the surgery', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the surgical procedure', max_length=200)),
                ('date', models.DateField(help_text='Date when the surgery was performed')),
                ('hospital', models.CharField(blank=True, help_text='Hospital where the surgery was performed', max_length=200, null=True)),
                ('surgeon', models.CharField(blank=True, help_text='Name of the surgeon who performed the surgery', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the surgery', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who had this surgery', on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surgery',
                'verbose_name_plural': 'Surgeries',
                'db_table': 'surgeries',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the allergy', primary_key=True, serialize=False)),
                ('allergen', models.CharField(help_text='Substance that causes the allergic reaction', max_length=200)),
                ('reaction', models.CharField(help_text='Description of the allergic reaction', max_length=500)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', help_text='Severity level of the allergic reaction', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the allergy', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who has this allergy', on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'db_table': 'allergies',
                'ordering': ['-severity', 'allergen'],
                'unique_together': {('user', 'allergen')},
            },
        ),
    ]
