# Generated by Django 5.2.7 on 2025-10-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('medication', 'Medication Reminder'), ('health-tip', 'Health Tip'), ('sync', 'Sync Complete'), ('general', 'General')], help_text='Type of notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('medication', 'Medication Reminder'), ('health-tip', 'Health Tip'), ('sync', 'Sync Complete'), ('general', 'General')], help_text='Type of notification this preference applies to', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('medication', 'Medication Reminder'), ('health-tip', 'Health Tip'), ('sync', 'Sync Complete'), ('general', 'General')], help_text='Type of notification this template is for', max_length=50),
        ),
    ]
